# Generated by Django 4.0.3 on 2022-09-14 15:13

import django.core.validators
from django.db import migrations, models
import management.models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='expirationDate',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='nDocumento',
        ),
        migrations.AddField(
            model_name='sale',
            name='address',
            field=models.CharField(blank=True, max_length=254, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='sale',
            name='nDocument',
            field=models.CharField(blank=True, max_length=20, verbose_name='Número de Documento / NIT'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='file',
            field=models.FileField(upload_to='backup', validators=[management.models.validate_file_extension], verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='name',
            field=models.CharField(blank=True, default='Copia de Seguridad', max_length=200, verbose_name='Nombre del Archivo'),
        ),
        migrations.AlterField(
            model_name='detailbuy',
            name='amount',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='detailbuy',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='detailsale',
            name='amount',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='product/Logo.png', null=True, upload_to='product', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unitMeasurement',
            field=models.CharField(choices=[('unit', 'Unidad'), ('pound', 'Lb'), ('kilogram', 'Kg'), ('litre', 'L')], default='unit', max_length=30, verbose_name='Unidad de medida'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='client',
            field=models.CharField(blank=True, max_length=50, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(default='subcategory/Logo.png', null=True, upload_to='subcategory', verbose_name='Imagen'),
        ),
    ]
