# Generated by Django 4.0.4 on 2022-09-14 21:06

from django.db import migrations, models
import management.models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_detailsale_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='file',
            field=models.FileField(upload_to='backup', validators=[management.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='backup',
            name='name',
            field=models.CharField(blank=True, default='Copia de Seguridad', max_length=200),
        ),
    ]
