# Generated by Django 4.0.4 on 2022-09-14 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_alter_backup_file_alter_backup_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(db_column='Nombre', max_length=50, verbose_name='Nombre'),
        ),
    ]
